// Package commitment provides shared helper implementations for commitment
// backends. Helpers in this file are stateless and do not own cache state.
package commitment

import (
	"fmt"

	"github.com/dewebprotocol/malt/core/types/arcset"
	cid "github.com/ipfs/go-cid"
)

// ProverFunc proves a single path against a commitment.
type ProverFunc func(path string) (cid.Cid, []byte, error)

// VerifierFunc verifies a single path proof against a commitment.
type VerifierFunc func(path string, value cid.Cid, proof []byte) (bool, error)

// BatchProve generates independent proofs for the provided paths.
func BatchProve(paths []string, prove ProverFunc) (map[string]arcset.BatchProofEntry, error) {
	if len(paths) == 0 {
		return nil, fmt.Errorf("paths is empty")
	}

	results := make(map[string]arcset.BatchProofEntry, len(paths))
	for _, path := range paths {
		target, proof, err := prove(path)
		if err != nil {
			return nil, fmt.Errorf("failed to prove path %s: %w", path, err)
		}
		results[path] = arcset.BatchProofEntry{
			Target: target,
			Proof:  proof,
		}
	}
	return results, nil
}

// BatchVerify verifies independent proofs generated by BatchProve.
func BatchVerify(proofs map[string]arcset.BatchProofEntry, verify VerifierFunc) (bool, error) {
	for path, entry := range proofs {
		ok, err := verify(path, entry.Target, entry.Proof)
		if err != nil {
			return false, fmt.Errorf("failed to verify path %s: %w", path, err)
		}
		if !ok {
			return false, nil
		}
	}
	return true, nil
}

// AggregateProve packages independent proofs into a single aggregated payload.
// It does not compress proofs; it simply keeps them together with their paths
// and targets.
func AggregateProve(paths []string, prove ProverFunc) (*arcset.AggregatedProof, error) {
	if len(paths) == 0 {
		return nil, fmt.Errorf("paths is empty")
	}

	targets := make([]cid.Cid, len(paths))
	proofs := make([][]byte, len(paths))
	for i, path := range paths {
		target, proof, err := prove(path)
		if err != nil {
			return nil, fmt.Errorf("failed to prove path %s: %w", path, err)
		}
		targets[i] = target
		proofs[i] = append([]byte(nil), proof...)
	}

	return &arcset.AggregatedProof{
		Paths:   append([]string(nil), paths...),
		Targets: targets,
		Proofs:  proofs,
	}, nil
}

// AggregateVerify verifies an aggregated collection of independent proofs.
func AggregateVerify(aggProof *arcset.AggregatedProof, verify VerifierFunc) (bool, error) {
	if aggProof == nil || len(aggProof.Paths) == 0 {
		return false, fmt.Errorf("invalid aggregated proof")
	}
	if len(aggProof.Paths) != len(aggProof.Targets) || len(aggProof.Paths) != len(aggProof.Proofs) {
		return false, fmt.Errorf("aggregated proof size mismatch")
	}

	for i, path := range aggProof.Paths {
		ok, err := verify(path, aggProof.Targets[i], aggProof.Proofs[i])
		if err != nil {
			return false, fmt.Errorf("failed to verify path %s: %w", path, err)
		}
		if !ok {
			return false, nil
		}
	}
	return true, nil
}

// FindPathIndex finds the index of a path in a sorted path slice.
func FindPathIndex(paths []string, path string) (int, bool) {
	low, high := 0, len(paths)-1
	for low <= high {
		mid := (low + high) / 2
		if paths[mid] == path {
			return mid, true
		}
		if paths[mid] < path {
			low = mid + 1
		} else {
			high = mid - 1
		}
	}
	return -1, false
}
